import Head from "next/head";
import Link from "next/link";
import Header from "./components/header/Header";
import SearchBar from "./components/searchbar/SearchBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <SearchBar />
        <Header />
      </main>
    </div>
  );
}
